[color-theme]
name = "Gruvbox Dark"

[color-theme.base]
white = "#ebdbb2"
black = "#1d2021"
grey = "#a89984"
blue = "#458588"
red = "#cc241d"
yellow = "#fabd2f"
orange = "#d79921"
green = "#98971a"
purple = "#d3869b"
cyan = "#689d6a"
magenta = "#b16286"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#928374"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#282828"
"activity.current" = "$black"
"completion.background" = "#282828"
"completion.current" = "#32302f"
"editor.background" = "$black"
"editor.caret" = "#fbf1c7"
"editor.current_line" = "#a8998422"
"editor.dim" = "#665c54"
"editor.drag_drop_background" = "#07667855"
"editor.drag_drop_tab_background" = "#07667855"
"editor.focus" = "#ebdbb2"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#3c3836"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#cc241d20"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#1d202120"
"error_lens.other.foreground" = "#504945"
"error_lens.warning.background" = "#50494520"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#32302f"
"inlay_hint.background" = "#28282837"
"inlay_hint.foreground" = "#665c54"
"lapce.border" = "#282828"
"lapce.button.primary.background" = "#b8bb26"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#282828"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#32302f"
"lapce.plugin.author" = "#fbf1c7"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#fbf1c7"
"lapce.remote.connected" = "#b8bb26"
"lapce.remote.connecting" = "#d79921"
"lapce.remote.disconnected" = "#fb4934"
"lapce.remote.local" = "#83a598"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#83a598"
"lapce.tab.inactive.background" = "#282828"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#83a59877"
"lapce.tab.separator" = ""
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#282828"
"palette.current.background" = "#32302f"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#282828"
"panel.current" = "#504945"
"panel.hovered" = "#83a59888"
"source_control.added" = "#b8bb2688"
"source_control.modified" = "#45858888"
"source_control.removed" = "#83a59866"
"status.background" = "#282828"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "$black"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true

