[color-theme]
name = "Gruvbox Light"

[color-theme.base]
white = "#3c3836"
black = "#fbf1c7"
grey = "#7c6f64"
blue = "#458588"
red = "#cc241d"
yellow = "#d79921"
orange = "#d65d0e"
green = "#98971a"
purple = "#8f3f71"
cyan = "#689d6a"
magenta = "#b16286"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#928374"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$red"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = "$black"
"completion.background" = "#d5c4a1"
"completion.current" = "$blue"
"completion_lens.foreground" = "#d5c4a1"
"editor.background" = "$black"
"editor.caret" = "$grey"
"editor.current_line" = "#7c6f6422"
"editor.dim" = "#bdae93"
"editor.drag_drop_background" = "#07667855"
"editor.drag_drop_tab_background" = "#07667855"
"editor.focus" = "#3c3836"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#ebdbb2"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#cc241d20"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#f9f5d720"
"error_lens.other.foreground" = "#d5c4a1"
"error_lens.warning.background" = "#50494520"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#f2e5bc"
"inlay_hint.background" = "#fbf1c737"
"inlay_hint.foreground" = "#bdae93"
"lapce.border" = "#d5c4a1"
"lapce.button.primary.background" = "#79740e"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#f2e5bc"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#f2e5bc"
"lapce.plugin.author" = "#282828"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#282828"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$orange"
"lapce.remote.disconnected" = "$red"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$blue"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "#ebdbb2"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$blue"
"lapce.tab.inactive.background" = "#fbf1c7"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "$grey"
"lapce.tab.separator" = "#f2e5bc"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#fbf1c7"
"palette.current.background" = "#f2e5bc"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "#fbf1c7"
"panel.current" = "#ffffff"
"panel.current.background" = "#7c6f6422"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "$blue"
"panel.foreground" = "$white"
"panel.foreground.dim" = "$purple"
"panel.hovered" = "#83a59888"
"panel.hovered.background" = "#d5c4a1"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "$purple"
"source_control.added" = "$green"
"source_control.modified" = "$blue"
"source_control.removed" = "$red"
"status.background" = "#fbf1c7"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal" = "$blue"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal" = "$purple"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual" = "$yellow"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "$black"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
