name = "gruvbox"
version = "0.1.1"
author = "NachiketNamjoshi"
display-name = "Gruvbox"
description = "The Iconic Gruvbox Theme"
icon = "gruvbox.png"
repository = "https://github.com/NachiketNamjoshi/lapce-gruvbox"
color-themes = ["gruvbox-dark.toml", "gruvbox-light.toml"]
