name = "gruvbox"
display-name = "Gruvbox"
description = "The Iconic Gruvbox Theme"
version = "0.1.0"
author = "Nachiket Namjoshi"
repository = "https://github.com/NachiketNamjoshi/lapce-gruvbox"
themes = ["gruvbox-dark.toml"]
